export enum COLOR {
  TEXT = 'text',
  LIGHT_TEXT = 'lightText',
  BACKGROUND = 'background',
  TRANSPARENT = 'transparent',
  PRIMARY = 'primary',
  TEXT_ON_PRIMARY = 'textOnPrimary',
  PRIMARY_HIGHLIGHT = 'primaryHighlight',
  SECONDARY = 'secondary',
  TEXT_ON_SECONDARY = 'textOnSecondary',
  SECONDARY_HIGHLIGHT = 'secondaryHighlight',
  WHITE = 'white',
  BLACK = 'black',
  DARK_GRAY = 'darkGray',
  GRAY = 'gray',
  LIGHT_GRAY = 'lightGray',
  EXTRA_LIGHT_GRAY = 'extraLightGray',
  EXTRA_EXTRA_LIGHT_GRAY = 'extraExtraLightGray',
  ND_BLUE = 'ndBlue',
  ND_BLUE_DARK = 'ndBlueDark',
  ND_BLUE_LIGHT = 'ndBlueLight',
  ND_BLUE_BRIGHT = 'ndBlueBright',
  ND_GOLD = 'ndGold',
  ND_GOLD_LIGHT = 'ndGoldLight',
  ND_GOLD_DARK = 'ndGoldDark',
  ND_SKY_BLUE = 'ndSkyBlue',
  ND_SKY_BLUE_DARK = 'ndSkyBlueDark',
  ND_METALLIC_GOLD = 'ndMetallicGold',
  ND_PROVOST_BLUE = 'ndProvostBlue',
  ND_SECONDARY_1 = 'ndSecondary1',
  ND_SECONDARY_2 = 'ndSecondary2',
  ND_SECONDARY_3 = 'ndSecondary3',
  ND_SECONDARY_4 = 'ndSecondary4',
  ND_SECONDARY_5 = 'ndSecondary5',
  ND_SECONDARY_6 = 'ndSecondary6',
  ND_TERTIARY_1 = 'ndTertiary1',
  ND_TERTIARY_2 = 'ndTertiary2',
  ND_TERTIARY_3 = 'ndTertiary3',
  ND_TERTIARY_4 = 'ndTertiary4',
  ND_TERTIARY_5 = 'ndTertiary5',
  ND_TERTIARY_6 = 'ndTertiary6',
  ALERT_INFORMATIONAL_BG = 'alertInformationalBg',
  ALERT_INFORMATIONAL_BORDER = 'alertInformationalBorder',
  ALERT_INFORMATIONAL_YELLOW_BG = 'alertInformationalYellowBg',
  ALERT_INFORMATIONAL_YELLOW_BORDER = 'alertInformationalYellowBorder',
  ALERT_WARNING_BG = 'alertWarningBg',
  ALERT_WARNING_BORDER = 'alertWarningBorder',
}

export const colors: {
  [key in COLOR]: string
} = {
  [COLOR.TEXT]: '#333333',
  [COLOR.LIGHT_TEXT]: '#767676',
  [COLOR.BACKGROUND]: '#ffffff',
  [COLOR.TRANSPARENT]: 'rgba(0,0,0,0)',
  [COLOR.PRIMARY]: '#0c2340',
  [COLOR.TEXT_ON_PRIMARY]: '#ffffff',
  [COLOR.PRIMARY_HIGHLIGHT]: '#000d1d',
  [COLOR.SECONDARY]: '#d39f10',
  [COLOR.SECONDARY_HIGHLIGHT]: '#ddcc70',
  [COLOR.TEXT_ON_SECONDARY]: '#040401',
  [COLOR.WHITE]: '#ffffff',
  [COLOR.BLACK]: '#000000',
  [COLOR.DARK_GRAY]: '#333333',
  [COLOR.GRAY]: '#767676',
  [COLOR.LIGHT_GRAY]: '#d2d2d2',
  [COLOR.EXTRA_LIGHT_GRAY]: '#e2e2e2',
  [COLOR.EXTRA_EXTRA_LIGHT_GRAY]: '#f2f2f2',
  [COLOR.ND_GOLD]: '#ae9142',
  [COLOR.ND_GOLD_LIGHT]: '#d39f10',
  [COLOR.ND_GOLD_DARK]: '#8c7535',
  [COLOR.ND_BLUE]: '#0c2340',
  [COLOR.ND_BLUE_DARK]: '#081629',
  [COLOR.ND_BLUE_LIGHT]: '#143865',
  [COLOR.ND_BLUE_BRIGHT]: '#1c4f8f',
  [COLOR.ND_SKY_BLUE]: '#e1e8f2',
  [COLOR.ND_SKY_BLUE_DARK]: '#c1cddd',
  [COLOR.ND_METALLIC_GOLD]: '#ae9142',
  [COLOR.ND_PROVOST_BLUE]: '#002a5d',
  [COLOR.ND_SECONDARY_1]: '#5aabbc',
  [COLOR.ND_SECONDARY_2]: '#999623',
  [COLOR.ND_SECONDARY_3]: '#5f1709',
  [COLOR.ND_SECONDARY_4]: '#465510',
  [COLOR.ND_SECONDARY_5]: '#f6e7a1',
  [COLOR.ND_SECONDARY_6]: '#302205',
  [COLOR.ND_TERTIARY_1]: '#00823E',
  [COLOR.ND_TERTIARY_2]: '#4a3651',
  [COLOR.ND_TERTIARY_3]: '#ffcf01',
  [COLOR.ND_TERTIARY_4]: '#aa272f',
  [COLOR.ND_TERTIARY_5]: '#5a412f',
  [COLOR.ND_TERTIARY_6]: '#ba6f2e',
  [COLOR.ALERT_INFORMATIONAL_BG]: '#ffb073',
  [COLOR.ALERT_INFORMATIONAL_BORDER]: '#ad7950',
  [COLOR.ALERT_INFORMATIONAL_YELLOW_BG]: '#f8e999',
  [COLOR.ALERT_INFORMATIONAL_YELLOW_BORDER]: '#b3a871',
  [COLOR.ALERT_WARNING_BG]: '#fc7279',
  [COLOR.ALERT_WARNING_BORDER]: '#ad5458',
}
